#!/bin/bash
source /cvmfs/cms.cern.ch/cmsset_default.sh
export SCRAM_ARCH=slc6_amd64_gcc481
if [ -r CMSSW_7_1_14/src ] ; then 
 echo release CMSSW_7_1_14 already exists
else
scram p CMSSW CMSSW_7_1_14
fi
cd CMSSW_7_1_14/src
eval `scram runtime -sh`

curl -s --insecure https://cms-pdmv.cern.ch/mcm/public/restapi/requests/get_fragment/SMP-RunIIWinter15wmLHE-00072 --retry 2 --create-dirs -o Configuration/GenProduction/python/SMP-RunIIWinter15wmLHE-00072-fragment.py 
[ -s Configuration/GenProduction/python/SMP-RunIIWinter15wmLHE-00072-fragment.py ] || exit $?;

scram b
cd ../../
cmsDriver.py Configuration/GenProduction/python/SMP-RunIIWinter15wmLHE-00072-fragment.py --fileout file:SMP-RunIIWinter15wmLHE-00072.root --mc --eventcontent LHE --datatier LHE --conditions MCRUN2_71_V1::All --step LHE --python_filename SMP-RunIIWinter15wmLHE-00072_1_cfg.py --no_exec --customise Configuration/DataProcessing/Utils.addMonitoring -n 960 || exit $? ; 

